### ISSUE TITLE
Request: Filter in the Data tab

### ISSUE THREAD

**Issue by scippie75** [ragnar-lodbrok/meow-sql#61]
What I find super useful in HeidiSQL is the filter block in the Data tab. It will add a LIKE '%xxx%' for every column in the query to select the data. You can also set the filter manually on the left, but I almost never use that.
Also changing the limit of the query to see more or less rows is a handy one to have.

So if you could add that functionality, that would really be so much appreciated!

**Comment by ragnar-lodbrok** [comment]
@scippie75 
OK, I did it, check master. You can activate it with Ctrl+Alt+F. 
You can also optionally use regexps, many features are supported e.g. use `^A` to match all strarting with `A`, `abc|def` for `abc` or `def` etc. By default all matches using wildcard so you don't need to input `*`.

FYI, Heidi allow to filter not only Data tab, but Query results and in fact any tables, but I did only Data tab for now.
Would be nice if you could test it since I changed a lot of things there.

> Also changing the limit of the query to see more or less rows is a handy one to have.
Please make another issue.

**Comment by scippie75** [comment]
A first test seemed to work fine, great!
